"""Telegram Bot handlers for YouTube Shadowing Transcript Bot."""

import os
import re
import tempfile

from telegram import Update
from telegram.ext import ContextTypes
from telegram.constants import ParseMode

import config
import transcript as tl


def _is_youtube_url(text: str) -> bool:
    """Quick check if text looks like a YouTube URL."""
    patterns = [
        "youtube.com/watch",
        "youtu.be/",
        "youtube.com/shorts/",
        "youtube.com/embed/",
        "youtube.com/live/",
    ]
    return any(p in text for p in patterns)


def _clean_filename(title: str) -> str:
    """Sanitize a string for use as a filename."""
    safe = re.sub(r'[\\/:*?"<>|]', "_", title)
    safe = re.sub(r'[_\s]+', "_", safe).strip("_")
    return safe or "transcript"


def _build_html(
    title: str,
    video_id: str,
    segments: list,
    language: str,
    is_generated: bool = False,
) -> str:
    """Build a self-contained HTML transcript page, mobile-friendly."""
    segment_count = len(segments)
    badge = "AUTO-GENERATED" if is_generated else "MANUAL"
    lines_html = ""
    for seg in segments:
        ts = tl.format_ts(seg["start"])
        secs = int(seg["start"])
        url_ts = f"https://youtube.com/watch?v={video_id}&t={secs}s"
        lines_html += (
            f'      <tr>\n'
            f'        <td class="ts">\n'
            f'          <a href="{url_ts}" target="_blank">{ts}</a>\n'
            f'        </td>\n'
            f'        <td class="text">{seg["text"]}</td>\n'
            f'      </tr>\n'
        )

    safe_title = (title or f"Video {video_id}").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    html = f"""<!DOCTYPE html>
<html lang="{language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{safe_title} — Shadowing Transcript</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
      background: #0d1117;
      color: #e6edf3;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
      line-height: 1.6;
      padding: 16px;
      max-width: 800px;
      margin: 0 auto;
    }}
    h1 {{
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 4px;
      word-break: break-word;
    }}
    .meta {{
      color: #8b949e;
      font-size: 0.85rem;
      margin-bottom: 20px;
    }}
    .meta a {{ color: #58a6ff; text-decoration: none; }}
    .meta a:hover {{ text-decoration: underline; }}
    table {{
      width: 100%;
      border-collapse: collapse;
    }}
    tr:hover {{ background: #161b22; }}
    td {{
      padding: 6px 8px;
      vertical-align: top;
      border-bottom: 1px solid #21262d;
    }}
    td.ts {{
      white-space: nowrap;
      width: 60px;
      text-align: right;
      font-family: "SF Mono", "Cascadia Code", monospace;
      font-size: 0.8rem;
    }}
    td.ts a {{ color: #58a6ff; text-decoration: none; }}
    td.ts a:hover {{ text-decoration: underline; }}
    td.text {{
      font-size: 1rem;
      color: #e6edf3;
    }}
    .footer {{
      text-align: center;
      color: #484f58;
      font-size: 0.75rem;
      margin-top: 24px;
      padding-top: 12px;
      border-top: 1px solid #21262d;
    }}
    @media (prefers-color-scheme: light) {{
      body {{ background: #ffffff; color: #1f2328; }}
      tr:hover {{ background: #f6f8fa; }}
      td {{ border-bottom-color: #d0d7de; }}
      td.text {{ color: #1f2328; }}
      .meta {{ color: #656d76; }}
      .footer {{ color: #8b949e; border-top-color: #d0d7de; }}
    }}
  </style>
</head>
<body>
  <h1>{safe_title}</h1>
  <div class="meta">
    {segment_count} lines &middot;
    Language: {language} &middot; {badge} &middot;
    <a href="https://youtube.com/watch?v={video_id}" target="_blank">Watch on YouTube</a>
  </div>
  <table>
{lines_html}  </table>
  <div class="footer">
    Generated by YouTube Shadowing Bot &middot; {video_id}
  </div>
</body>
</html>"""
    return html


async def _send_html_file(
    update: Update, html_content: str, filename: str
) -> None:
    """Send HTML content as a .html file attachment."""
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".html", delete=False, encoding="utf-8"
    ) as f:
        f.write(html_content)
        tmp_path = f.name

    try:
        with open(tmp_path, "rb") as f:
            await update.message.reply_document(
                document=f,
                filename=filename,
                caption=f"📄 `{filename}`",
                parse_mode=ParseMode.MARKDOWN,
            )
    finally:
        os.unlink(tmp_path)


def _split_text(text: str, max_len: int = config.MAX_MESSAGE_LENGTH) -> list:
    """Split long text into chunks, keeping timestamp lines intact."""
    lines = text.split("\n")
    chunks = []
    current = []
    current_len = 0

    for line in lines:
        line_len = len(line) + 1
        if current_len + line_len > max_len and current:
            chunks.append("\n".join(current))
            current = [line]
            current_len = line_len
        else:
            current.append(line)
            current_len += line_len

    if current:
        chunks.append("\n".join(current))

    return chunks


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Welcome message."""
    welcome = (
        "🎬 *YouTube Shadowing Transcript Bot*\n\n"
        "傳送 YouTube 網址，我幫你提取字幕（含時間戳記），"
        "方便你練習 English Shadowing！\n\n"
        "🔹 *支援格式：*\n"
        "  • 一般影片: `youtube.com/watch?v=...`\n"
        "  • 短網址: `youtu.be/...`\n"
        "  • Shorts: `youtube.com/shorts/...`\n\n"
        "🔹 *指令：*\n"
        "  `/lang zh-Hans` — 切換字幕語言 (預設 en)\n"
        "  `/html` — 切換強制 HTML 匯出模式\n"
        "  `/start` — 重新顯示此訊息\n\n"
        "🔹 *輸出：*\n"
        "  • 短字幕 → 直接顯示在聊天中\n"
        "  • 長字幕（>20 段）→ 自動匯出為 `.html` 檔案\n"
        "  • `/html` 開啟後 → 一律匯出 HTML\n"
        "  檔名使用影片原始標題\n\n"
        "🔹 *範例：*\n"
        "  傳送 `https://youtu.be/dQw4w9WgXcQ`\n"
        "  → 回傳完整時間軸字幕 / HTML 檔案"
    )
    await update.message.reply_text(welcome, parse_mode=ParseMode.MARKDOWN)


async def set_language(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Set transcript language for the current chat."""
    if not context.args:
        await update.message.reply_text(
            "用法: `/lang en` （例如: en, zh-Hans, ja, ko, es）",
            parse_mode=ParseMode.MARKDOWN,
        )
        return

    lang = context.args[0]
    context.chat_data["lang"] = lang
    await update.message.reply_text(f"✅ 字幕語言已切換為: `{lang}`")


async def toggle_html(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Toggle force-HTML mode."""
    current = context.chat_data.get("force_html", False)
    context.chat_data["force_html"] = not current
    mode = (
        "✅ 已開啟強制 HTML 模式，下次一率匯出 HTML 檔案"
        if not current
        else "✅ 已關閉強制 HTML 模式，短字幕直接顯示"
    )
    await update.message.reply_text(mode)


async def handle_url(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle a YouTube URL message — fetch and return transcript."""
    text = update.message.text.strip()

    # Send "processing" message
    status_msg = await update.message.reply_text("⏳ 正在擷取字幕，請稍候...")

    video_id = tl.extract_video_id(text)
    lang = context.chat_data.get("lang", config.TRANSCRIPT_LANGUAGE)

    result = tl.fetch_transcript(video_id, lang)

    if not result["success"]:
        await status_msg.edit_text(
            f"❌ 無法取得字幕：{result['error']}\n\n"
            f"可能原因：\n"
            f"• 該影片未開啟字幕功能\n"
            f"• 語言 `{lang}` 無對應字幕\n"
            f"• 影片為私人／不公開\n\n"
            f"提示：試試 `/lang en` 或 `/lang zh-Hant` 切換語言後重新傳送",
        )
        return

    await status_msg.delete()

    title = result.get("title") or video_id
    safe_name = _clean_filename(title)
    force_html = context.chat_data.get("force_html", False)
    actual_lang = result.get("language", lang)

    # Decide: inline text or HTML file
    if force_html or result["segment_count"] > 20:
        # Build & send HTML file
        html_content = _build_html(
            title=title,
            video_id=video_id,
            segments=result["segments"],
            language=actual_lang,
            is_generated=result.get("is_generated", False),
        )
        fname = f"{safe_name}.html"

        preview = (
            f"📺 *{title}*\n"
            f"📝 {result['segment_count']} 段字幕 (🌐 {actual_lang})\n"
            f"📄 匯出為 `{fname}`"
        )
        await update.message.reply_text(preview, parse_mode=ParseMode.MARKDOWN)
        await _send_html_file(update, html_content, fname)
    else:
        # Short transcript — send as inline message
        header = (
            f"📺 *{title}*\n"
            f"📝 {result['segment_count']} 段字幕 (🌐 {actual_lang})\n"
        )
        await update.message.reply_text(header, parse_mode=ParseMode.MARKDOWN)

        timestamped = result["timestamped_text"]
        chunks = _split_text(timestamped)
        for chunk in chunks:
            await update.message.reply_text(
                f"```\n{chunk}\n```",
                parse_mode=ParseMode.MARKDOWN,
            )


async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Route incoming messages."""
    if _is_youtube_url(update.message.text):
        await handle_url(update, context)
    else:
        await update.message.reply_text(
            "❓ 請傳送 YouTube 網址，或使用 `/start` 查看說明。"
        )