"""YouTube transcript fetching and video metadata.

Primary: youtube-transcript-api for subtitles.
No translation — returns whatever transcript is available.
yt-dlp called via subprocess only for video title.
"""

import re
import subprocess
import sys
from typing import Optional


def extract_video_id(url_or_id: str) -> str:
    """Extract the 11-character video ID from various YouTube URL formats."""
    url_or_id = url_or_id.strip()
    patterns = [
        r"(?:v=|youtu\.be/|shorts/|embed/|live/)([a-zA-Z0-9_-]{11})",
        r"^([a-zA-Z0-9_-]{11})$",
    ]
    for pattern in patterns:
        match = re.search(pattern, url_or_id)
        if match:
            return match.group(1)
    return url_or_id


def format_ts(seconds: float) -> str:
    """Convert seconds to MM:SS or H:MM:SS format."""
    total = int(seconds)
    h, remainder = divmod(total, 3600)
    m, s = divmod(remainder, 60)
    if h > 0:
        return f"{h}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"


def get_video_title(video_id: str) -> Optional[str]:
    """Fetch video title via yt-dlp (silent, fast).

    Returns the title string, or None on failure.
    """
    try:
        url = f"https://youtube.com/watch?v={video_id}"
        result = subprocess.run(
            ["yt-dlp", "--print", "title", "--no-download", url],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


def _find_best_transcript(video_id: str, preferred_lang: str):
    """Find the best available transcript.

    Returns (transcript_object, actual_language_code) or None.
    Uses the low-level .list() API to check availability.
    """
    from youtube_transcript_api._api import YouTubeTranscriptApi

    api = YouTubeTranscriptApi()
    transcript_list = api.list(video_id)

    # 1. Try preferred language (exact match)
    try:
        t = transcript_list.find_transcript([preferred_lang])
        return t, preferred_lang
    except Exception:
        pass

    # 2. Try manually created transcripts (best quality)
    try:
        t = transcript_list.find_manually_created_transcript(
            [preferred_lang]
        )
        return t, t.language_code
    except Exception:
        pass

    # 3. Fall back to any available transcript
    for t in transcript_list:
        return t, t.language_code

    return None, None


def fetch_transcript(video_id: str, language: str = "en") -> dict:
    """Fetch transcript and return structured result.

    Tries the requested language first, then falls back to any
    available transcript. Never translates.

    Returns: {
        "success": True/False,
        "video_id": "...",
        "title": "...",           # video title (or None)
        "language": "...",        # actual language code used
        "language_name": "...",   # human-readable language name
        "is_generated": bool,     # auto-generated by YouTube?
        "segments": [{...}],
        "full_text": "...",
        "timestamped_text": "...",
        "error": "..."            # only on failure
    }
    """
    try:
        transcript_obj, actual_lang = _find_best_transcript(
            video_id, language
        )

        if transcript_obj is None:
            return {
                "success": False,
                "video_id": video_id,
                "error": "No transcript available for this video.",
            }

        result = transcript_obj.fetch()
        segments = [
            {"text": seg.text, "start": seg.start, "duration": seg.duration}
            for seg in result
        ]

        lang_code = actual_lang or language
        lang_name = getattr(transcript_obj, "language", lang_code)

    except ImportError:
        return {
            "success": False,
            "video_id": video_id,
            "error": "youtube-transcript-api not installed",
        }
    except Exception as e:
        print(f"[transcript] Error: {e}", file=sys.stderr)
        return {
            "success": False,
            "video_id": video_id,
            "error": str(e),
        }

    if not segments:
        return {
            "success": False,
            "video_id": video_id,
            "error": "No transcript segments found.",
        }

    # Get video title (best-effort)
    title = get_video_title(video_id)

    full_text = " ".join(seg["text"] for seg in segments)
    timestamped_lines = [
        f"{format_ts(seg['start'])}\t{seg['text']}" for seg in segments
    ]
    timestamped_text = "\n".join(timestamped_lines)

    return {
        "success": True,
        "video_id": video_id,
        "title": title,
        "language": lang_code,
        "language_name": lang_name,
        "is_generated": getattr(transcript_obj, "is_generated", False),
        "segment_count": len(segments),
        "segments": segments,
        "full_text": full_text,
        "timestamped_text": timestamped_text,
    }