name: CD

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy bots
        run: |
          bash /home/apollo/airteleBots/.github/scripts/deploy.sh